# Configuración de Dependabot para actualizaciones automáticas de dependencias
version: 2
updates:
  # Actualizaciones para dependencias Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 10
    reviewers:
      - "ssoto"
    assignees:
      - "ssoto"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignorar actualizaciones de versiones mayores que puedan romper compatibilidad
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]

  # Actualizaciones para dependencias de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5
    reviewers:
      - "ssoto"
    assignees:
      - "ssoto"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
